//! Automated setup, PJOrion-style: locate the client, drop the bundled agent
//! mod into it, and launch it. The universal agent `.mod` is embedded in the binary so
//! no Python 2.7 toolchain is needed at runtime.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Serialize;

/// Python 2.7 agent package generated by `mod/build.py` before the Tauri build.
const AGENT_MOD: &[u8] = include_bytes!("../resources/me.fuflo.wotrepl.mod");
const MTMOD_NAME: &str = "me.fuflo.wotrepl.mtmod";
const WOTMOD_NAME: &str = "me.fuflo.wotrepl.wotmod";

const EXES: [&str; 4] = ["Tanki.exe", "WorldOfTanks.exe", "WoT.exe", "wot.exe"];
const ROOTS: [&str; 8] = [
    "C:/Games",
    "C:/Program Files",
    "C:/Program Files (x86)",
    "D:/Games",
    "E:/Games",
    "U:/Games",
    "U:/Programs",
    "D:/",
];

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GameInfo {
    pub path: String,
    pub version: String,
    pub mods_version: String,
    pub exe: String,
    pub installed: bool,
}

pub(crate) fn app_data_root() -> PathBuf {
    let base = std::env::var("LOCALAPPDATA")
        .or_else(|_| std::env::var("APPDATA"))
        .unwrap_or_else(|_| ".".to_string());
    PathBuf::from(base).join("FufloWoTREPL")
}

pub fn default_buffer_dir_path() -> PathBuf {
    app_data_root().join("buffer")
}

/// Canonical jedi sys_path root for runtime-generated native-module stubs.
pub fn stubs_dir_path() -> PathBuf {
    app_data_root().join("stubs")
}

/// Persist runtime dump stubs as `<type>.pyi` files; returns the stubs dir.
pub fn write_stubs(stubs: &std::collections::HashMap<String, String>) -> Result<String, String> {
    let dir = stubs_dir_path();
    fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    for (module, body) in stubs {
        // Guard against path traversal from a module name.
        if module.is_empty() || module.contains(['/', '\\', '.', ':']) {
            continue;
        }
        fs::write(dir.join(format!("{module}.pyi")), body).map_err(|e| e.to_string())?;
    }
    Ok(dir.to_string_lossy().into_owned())
}

pub fn detect_games() -> Vec<GameInfo> {
    let mut out = Vec::new();
    let mut seen = std::collections::HashSet::new();
    for root in ROOTS {
        let Ok(entries) = fs::read_dir(Path::new(root)) else {
            continue;
        };
        for entry in entries.flatten() {
            push_if_game(&entry.path(), &mut out, &mut seen);
        }
    }
    for dir in registry_install_dirs() {
        push_if_game(&dir, &mut out, &mut seen);
    }
    out
}

fn push_if_game(dir: &Path, out: &mut Vec<GameInfo>, seen: &mut std::collections::HashSet<String>) {
    if let Some(info) = inspect_dir(dir) {
        if seen.insert(info.path.to_lowercase()) {
            out.push(info);
        }
    }
}

/// Validate a single directory as a game install (used by registry/FS detection
/// and the manual folder picker). Normalizes the path so the same install found
/// via different roots dedups cleanly.
pub fn inspect_dir(dir: &Path) -> Option<GameInfo> {
    let dir = normalize(dir);
    if !dir.is_dir() {
        return None;
    }
    let exe = game_exe(&dir)?;
    read_game(&dir, exe)
}

fn game_exe(dir: &Path) -> Option<&'static str> {
    EXES.iter().copied().find(|exe| dir.join(exe).is_file())
}

fn mod_name_for_exe(exe: &str) -> &'static str {
    if exe.eq_ignore_ascii_case("Tanki.exe") {
        MTMOD_NAME
    } else {
        WOTMOD_NAME
    }
}

/// Resolve to an absolute path and strip Windows' `\\?\` verbatim prefix.
fn normalize(dir: &Path) -> PathBuf {
    let resolved = fs::canonicalize(dir).unwrap_or_else(|_| dir.to_path_buf());
    let s = resolved.to_string_lossy();
    match s.strip_prefix(r"\\?\") {
        Some(rest) => PathBuf::from(rest),
        None => resolved,
    }
}

/// Game install dirs registered under the Uninstall hives (Lesta Game Center and
/// Wargaming.net Game Center both write `InstallLocation` there).
#[cfg(windows)]
fn registry_install_dirs() -> Vec<PathBuf> {
    use winreg::enums::{HKEY_CURRENT_USER, HKEY_LOCAL_MACHINE};
    use winreg::RegKey;

    const UNINSTALL: &str = r"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall";
    const UNINSTALL_WOW: &str = r"SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall";
    let hives = [
        (RegKey::predef(HKEY_LOCAL_MACHINE), UNINSTALL),
        (RegKey::predef(HKEY_LOCAL_MACHINE), UNINSTALL_WOW),
        (RegKey::predef(HKEY_CURRENT_USER), UNINSTALL),
    ];

    let mut dirs = Vec::new();
    for (hive, path) in hives {
        let Ok(uninstall) = hive.open_subkey(path) else {
            continue;
        };
        for name in uninstall.enum_keys().flatten() {
            let Ok(entry) = uninstall.open_subkey(&name) else {
                continue;
            };
            if let Ok(loc) = entry.get_value::<String, _>("InstallLocation") {
                let loc = loc.trim();
                if !loc.is_empty() {
                    dirs.push(PathBuf::from(loc));
                }
            }
        }
    }
    dirs
}

#[cfg(not(windows))]
fn registry_install_dirs() -> Vec<PathBuf> {
    Vec::new()
}

fn read_game(dir: &Path, exe: &str) -> Option<GameInfo> {
    let version = fs::read_to_string(dir.join("version.xml"))
        .ok()
        .and_then(|s| extract_version(&s))
        .unwrap_or_default();
    let mods_version = pick_mods_version(dir, &version);
    let installed = dir
        .join("mods")
        .join(&mods_version)
        .join(mod_name_for_exe(exe))
        .is_file();
    Some(GameInfo {
        path: dir.to_string_lossy().into_owned(),
        version,
        mods_version,
        exe: exe.to_string(),
        installed,
    })
}

/// Pull the `1.43.0.0` token out of `<version> v.1.43.0.0 #2244 </version>`.
fn extract_version(xml: &str) -> Option<String> {
    let idx = xml.find("v.")?;
    let tail = &xml[idx + 2..];
    let token: String = tail
        .chars()
        .take_while(|c| c.is_ascii_digit() || *c == '.')
        .collect();
    if token.split('.').count() >= 3 {
        Some(token)
    } else {
        None
    }
}

/// Prefer the exact `mods/<version>` folder; otherwise the lexically-greatest
/// version-like subfolder of `mods/`; otherwise the parsed version itself.
fn pick_mods_version(dir: &Path, version: &str) -> String {
    let mods = dir.join("mods");
    if !version.is_empty() && mods.join(version).is_dir() {
        return version.to_string();
    }
    let mut candidates: Vec<String> = fs::read_dir(&mods)
        .into_iter()
        .flatten()
        .flatten()
        .filter(|e| e.path().is_dir())
        .filter_map(|e| e.file_name().into_string().ok())
        .filter(|n| n.chars().next().is_some_and(|c| c.is_ascii_digit()))
        .collect();
    candidates.sort();
    candidates.pop().unwrap_or_else(|| version.to_string())
}

pub fn install_agent(game_dir: &str, mods_version: &str) -> Result<String, String> {
    if mods_version.trim().is_empty() {
        return Err("missing mods version".into());
    }
    let game_dir = PathBuf::from(game_dir);
    let exe = game_exe(&game_dir).ok_or_else(|| "not a supported WoT install".to_string())?;
    let mod_name = mod_name_for_exe(exe);
    let mods_dir = game_dir.join("mods").join(mods_version);
    fs::create_dir_all(&mods_dir).map_err(|e| e.to_string())?;
    // Drop any previous build of ours, including either game extension.
    if let Ok(entries) = fs::read_dir(&mods_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().into_owned();
            if name.starts_with("me.fuflo.wotrepl") || name.starts_with("me.wms.agent") {
                let _ = fs::remove_file(entry.path());
            }
        }
    }
    fs::write(mods_dir.join(mod_name), AGENT_MOD).map_err(|e| e.to_string())?;
    let buffer = default_buffer_dir_path();
    fs::create_dir_all(&buffer).map_err(|e| e.to_string())?;
    Ok(buffer.to_string_lossy().into_owned())
}

fn replay_extension(exe: &str) -> &'static str {
    if exe.eq_ignore_ascii_case("Tanki.exe") {
        "mtreplay"
    } else {
        "wotreplay"
    }
}

pub fn launch_game(game_dir: &str, exe: &str, replay: Option<&str>) -> Result<u32, String> {
    let exe_path = PathBuf::from(game_dir).join(exe);
    if !exe_path.is_file() {
        return Err(format!("launcher not found: {}", exe_path.display()));
    }
    let mut command = Command::new(&exe_path);
    command.current_dir(game_dir);
    if let Some(replay) = replay {
        let replay_path = Path::new(replay);
        if !replay_path.is_file() {
            return Err(format!("replay not found: {}", replay_path.display()));
        }
        let valid_extension = replay_path
            .extension()
            .and_then(|value| value.to_str())
            .is_some_and(|value| value.eq_ignore_ascii_case(replay_extension(exe)));
        if !valid_extension {
            return Err(format!("expected a .{} replay", replay_extension(exe)));
        }
        command.arg(replay_path);
    }
    command
        .spawn()
        .map(|child| child.id())
        .map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::{mod_name_for_exe, replay_extension, MTMOD_NAME, WOTMOD_NAME};

    #[test]
    fn picks_the_game_mod_extension() {
        assert_eq!(mod_name_for_exe("Tanki.exe"), MTMOD_NAME);
        for exe in ["WorldOfTanks.exe", "WoT.exe", "wot.exe"] {
            assert_eq!(mod_name_for_exe(exe), WOTMOD_NAME);
        }
    }

    #[test]
    fn picks_the_game_replay_extension() {
        assert_eq!(replay_extension("Tanki.exe"), "mtreplay");
        assert_eq!(replay_extension("WorldOfTanks.exe"), "wotreplay");
    }
}
