//! Automated setup, PJOrion-style: locate the client, drop the bundled agent
//! mod into it, and launch it. The universal agent `.mod` is embedded in the binary so
//! no Python 2.7 toolchain is needed at runtime.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Serialize;

/// Python 2.7 agent package generated by `mod/build.py` before the Tauri build.
const AGENT_MOD: &[u8] = include_bytes!("../resources/wotstat.repl.mod");
const MTMOD_EXTENSION: &str = "mtmod";
const WOTMOD_EXTENSION: &str = "wotmod";

const EXES: [&str; 4] = ["Tanki.exe", "WorldOfTanks.exe", "WoT.exe", "wot.exe"];
const ROOTS: [&str; 8] = [
    "C:/Games",
    "C:/Program Files",
    "C:/Program Files (x86)",
    "D:/Games",
    "E:/Games",
    "U:/Games",
    "U:/Programs",
    "D:/",
];

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GameInfo {
    pub path: String,
    pub version: String,
    pub mods_version: String,
    pub exe: String,
    pub installed: bool,
}

pub(crate) fn app_data_root() -> PathBuf {
    #[cfg(windows)]
    let base = std::env::var("LOCALAPPDATA")
        .or_else(|_| std::env::var("APPDATA"))
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("."));
    #[cfg(target_os = "macos")]
    let base = std::env::var("HOME")
        .map(|home| PathBuf::from(home).join("Library/Application Support"))
        .unwrap_or_else(|_| PathBuf::from("."));
    #[cfg(all(unix, not(target_os = "macos")))]
    let base = std::env::var("XDG_DATA_HOME")
        .map(PathBuf::from)
        .or_else(|_| std::env::var("HOME").map(|home| PathBuf::from(home).join(".local/share")))
        .unwrap_or_else(|_| PathBuf::from("."));
    #[cfg(not(any(windows, unix)))]
    let base = PathBuf::from(".");
    base.join("WotStatWoTREPL")
}

pub fn detect_games() -> Vec<GameInfo> {
    let mut out = Vec::new();
    let mut seen = std::collections::HashSet::new();
    for root in ROOTS {
        let Ok(entries) = fs::read_dir(Path::new(root)) else {
            continue;
        };
        for entry in entries.flatten() {
            push_if_game(&entry.path(), &mut out, &mut seen);
        }
    }
    for dir in registry_install_dirs() {
        push_if_game(&dir, &mut out, &mut seen);
    }
    out
}

fn push_if_game(dir: &Path, out: &mut Vec<GameInfo>, seen: &mut std::collections::HashSet<String>) {
    if let Some(info) = inspect_dir(dir) {
        if seen.insert(info.path.to_lowercase()) {
            out.push(info);
        }
    }
}

/// Validate a single directory as a game install (used by registry/FS detection
/// and the manual folder picker). Normalizes the path so the same install found
/// via different roots dedups cleanly.
pub fn inspect_dir(dir: &Path) -> Option<GameInfo> {
    let dir = normalize(dir);
    if !dir.is_dir() {
        return None;
    }
    let exe = game_exe(&dir)?;
    read_game(&dir, exe)
}

/// Resolve a running game executable back to its installation root.
///
/// Wargaming's root executable is a short-lived launcher; the long-lived game
/// process runs from `win32/` or `win64/`. Prefer the parent installation in
/// that layout so process tracking does not invent a second, versionless game.
pub(crate) fn inspect_game_executable(executable: &Path) -> Option<GameInfo> {
    let executable = normalize(executable);
    let executable_name = executable.file_name()?.to_string_lossy();
    let process_dir = executable.parent()?;
    let architecture_dir = process_dir
        .file_name()
        .and_then(|name| name.to_str())
        .is_some_and(|name| {
            name.eq_ignore_ascii_case("win32") || name.eq_ignore_ascii_case("win64")
        });

    let parent_install = architecture_dir
        .then(|| process_dir.parent())
        .flatten()
        .and_then(inspect_dir)
        .filter(|game| executable_name.eq_ignore_ascii_case(&game.exe));
    parent_install.or_else(|| {
        inspect_dir(process_dir).filter(|game| executable_name.eq_ignore_ascii_case(&game.exe))
    })
}

fn game_exe(dir: &Path) -> Option<&'static str> {
    EXES.iter().copied().find(|exe| dir.join(exe).is_file())
}

fn mod_name_for_exe(exe: &str, agent_version: &str) -> String {
    let extension = if exe.eq_ignore_ascii_case("Tanki.exe") {
        MTMOD_EXTENSION
    } else {
        WOTMOD_EXTENSION
    };
    format!("wotstat.repl_{agent_version}.{extension}")
}

/// Resolve to an absolute path and strip Windows' `\\?\` verbatim prefix.
fn normalize(dir: &Path) -> PathBuf {
    let resolved = fs::canonicalize(dir).unwrap_or_else(|_| dir.to_path_buf());
    let s = resolved.to_string_lossy();
    match s.strip_prefix(r"\\?\") {
        Some(rest) => PathBuf::from(rest),
        None => resolved,
    }
}

/// Game install dirs registered under the Uninstall hives (Lesta Game Center and
/// Wargaming.net Game Center both write `InstallLocation` there).
#[cfg(windows)]
fn registry_install_dirs() -> Vec<PathBuf> {
    use winreg::enums::{HKEY_CURRENT_USER, HKEY_LOCAL_MACHINE};
    use winreg::RegKey;

    const UNINSTALL: &str = r"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall";
    const UNINSTALL_WOW: &str = r"SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall";
    let hives = [
        (RegKey::predef(HKEY_LOCAL_MACHINE), UNINSTALL),
        (RegKey::predef(HKEY_LOCAL_MACHINE), UNINSTALL_WOW),
        (RegKey::predef(HKEY_CURRENT_USER), UNINSTALL),
    ];

    let mut dirs = Vec::new();
    for (hive, path) in hives {
        let Ok(uninstall) = hive.open_subkey(path) else {
            continue;
        };
        for name in uninstall.enum_keys().flatten() {
            let Ok(entry) = uninstall.open_subkey(&name) else {
                continue;
            };
            if let Ok(loc) = entry.get_value::<String, _>("InstallLocation") {
                let loc = loc.trim();
                if !loc.is_empty() {
                    dirs.push(PathBuf::from(loc));
                }
            }
        }
    }
    dirs
}

#[cfg(not(windows))]
fn registry_install_dirs() -> Vec<PathBuf> {
    Vec::new()
}

fn read_game(dir: &Path, exe: &str) -> Option<GameInfo> {
    let version = fs::read_to_string(dir.join("version.xml"))
        .ok()
        .and_then(|s| extract_version(&s))
        .unwrap_or_default();
    let mods_version = pick_mods_version(dir, &version);
    let installed = dir
        .join("mods")
        .join(&mods_version)
        .join(mod_name_for_exe(exe, crate::APP_VERSION))
        .is_file();
    Some(GameInfo {
        path: dir.to_string_lossy().into_owned(),
        version,
        mods_version,
        exe: exe.to_string(),
        installed,
    })
}

/// Pull the `1.43.0.0` token out of `<version> v.1.43.0.0 #2244 </version>`.
fn extract_version(xml: &str) -> Option<String> {
    let idx = xml.find("v.")?;
    let tail = &xml[idx + 2..];
    let token: String = tail
        .chars()
        .take_while(|c| c.is_ascii_digit() || *c == '.')
        .collect();
    if token.split('.').count() >= 3 {
        Some(token)
    } else {
        None
    }
}

/// Prefer the exact `mods/<version>` folder; otherwise the lexically-greatest
/// version-like subfolder of `mods/`; otherwise the parsed version itself.
fn pick_mods_version(dir: &Path, version: &str) -> String {
    let mods = dir.join("mods");
    if !version.is_empty() && mods.join(version).is_dir() {
        return version.to_string();
    }
    let mut candidates: Vec<String> = fs::read_dir(&mods)
        .into_iter()
        .flatten()
        .flatten()
        .filter(|e| e.path().is_dir())
        .filter_map(|e| e.file_name().into_string().ok())
        .filter(|n| n.chars().next().is_some_and(|c| c.is_ascii_digit()))
        .collect();
    candidates.sort();
    candidates.pop().unwrap_or_else(|| version.to_string())
}

pub fn install_agent(
    game_dir: &str,
    mods_version: &str,
    agent_config: &[u8],
) -> Result<(), String> {
    if mods_version.trim().is_empty() {
        return Err("missing mods version".into());
    }
    let game_dir = PathBuf::from(game_dir);
    let exe = game_exe(&game_dir).ok_or_else(|| "not a supported WoT install".to_string())?;
    let mod_name = mod_name_for_exe(exe, crate::APP_VERSION);
    let mods_dir = game_dir.join("mods").join(mods_version);
    fs::create_dir_all(&mods_dir).map_err(|e| e.to_string())?;
    // Drop any previous build of ours, including either game extension.
    if let Ok(entries) = fs::read_dir(&mods_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().into_owned();
            if name.starts_with("wotstat.repl") || name.starts_with("me.wms.agent") {
                let _ = fs::remove_file(entry.path());
            }
        }
    }
    fs::write(mods_dir.join(mod_name), AGENT_MOD).map_err(|e| e.to_string())?;
    let config_dir = game_dir.join("mods").join("configs").join("wotstat-repl");
    fs::create_dir_all(&config_dir).map_err(|e| e.to_string())?;
    fs::write(config_dir.join("agent-network.json"), agent_config).map_err(|e| e.to_string())?;
    Ok(())
}

fn replay_extension(exe: &str) -> &'static str {
    if exe.eq_ignore_ascii_case("Tanki.exe") {
        "mtreplay"
    } else {
        "wotreplay"
    }
}

pub fn launch_game(game_dir: &str, exe: &str, replay: Option<&str>) -> Result<u32, String> {
    let exe_path = PathBuf::from(game_dir).join(exe);
    if !exe_path.is_file() {
        return Err(format!("launcher not found: {}", exe_path.display()));
    }
    let mut command = Command::new(&exe_path);
    command.current_dir(game_dir);
    if let Some(replay) = replay {
        let replay_path = Path::new(replay);
        if !replay_path.is_file() {
            return Err(format!("replay not found: {}", replay_path.display()));
        }
        let valid_extension = replay_path
            .extension()
            .and_then(|value| value.to_str())
            .is_some_and(|value| value.eq_ignore_ascii_case(replay_extension(exe)));
        if !valid_extension {
            return Err(format!("expected a .{} replay", replay_extension(exe)));
        }
        command.arg(replay_path);
    }
    command
        .spawn()
        .map(|child| child.id())
        .map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::{
        inspect_game_executable, install_agent, mod_name_for_exe, normalize, replay_extension,
    };

    #[test]
    fn picks_the_game_mod_extension() {
        assert_eq!(
            mod_name_for_exe("Tanki.exe", "1.1.0"),
            "wotstat.repl_1.1.0.mtmod"
        );
        for exe in ["WorldOfTanks.exe", "WoT.exe", "wot.exe"] {
            assert_eq!(mod_name_for_exe(exe, "1.1.0"), "wotstat.repl_1.1.0.wotmod");
        }
    }

    #[test]
    fn picks_the_game_replay_extension() {
        assert_eq!(replay_extension("Tanki.exe"), "mtreplay");
        assert_eq!(replay_extension("WorldOfTanks.exe"), "wotreplay");
    }

    #[test]
    fn installation_places_network_config_where_proton_can_see_it() {
        let root = std::env::temp_dir().join(format!("wms_install_{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&root).unwrap();
        std::fs::write(root.join("Tanki.exe"), b"").unwrap();
        let config = br#"{"token":"test"}"#;

        install_agent(root.to_str().unwrap(), "1.0", config).unwrap();

        assert!(root
            .join("mods/1.0")
            .join(format!("wotstat.repl_{}.mtmod", crate::APP_VERSION))
            .is_file());
        assert_eq!(
            std::fs::read(root.join("mods/configs/wotstat-repl/agent-network.json")).unwrap(),
            config
        );
        let _ = std::fs::remove_dir_all(root);
    }

    #[test]
    fn running_architecture_executable_maps_to_install_root() {
        let root = std::env::temp_dir().join(format!("wms_game_{}", uuid::Uuid::new_v4()));
        let win64 = root.join("win64");
        std::fs::create_dir_all(&win64).unwrap();
        std::fs::write(root.join("WorldOfTanks.exe"), b"").unwrap();
        std::fs::write(win64.join("WorldOfTanks.exe"), b"").unwrap();
        std::fs::write(
            root.join("version.xml"),
            b"<version> v.2.3.1.3 #1 </version>",
        )
        .unwrap();

        let game = inspect_game_executable(&win64.join("WorldOfTanks.exe")).unwrap();

        assert_eq!(game.path, normalize(&root).to_string_lossy());
        assert_eq!(game.exe, "WorldOfTanks.exe");
        assert_eq!(game.version, "2.3.1.3");
        assert_eq!(game.mods_version, "2.3.1.3");
        let _ = std::fs::remove_dir_all(root);
    }
}
